# Check all files in the folder including subdirectories

all: check-models check-tests check-docs

check-models:
    cd models && make check

check-tests:
    cd tests && make check

check-docs:
    cd docs && make check
